<a href="https://colab.research.google.com/github/Samanvith07/23CSBTB40/blob/main/Array1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Part 1 – Implement Basic Data Structures using Numpy, Pandas

In [4]:
import numpy as np
import pandas as pd
list1 = [1, 2, 3, 4, 5]
list2 = [1, 2, 3, 4, 5]
print(type(list1))
print(type(list2))


<class 'list'>
<class 'list'>


([1,2,3,4,5],list)

In [5]:
array1=np.array(list1)
print(array1)
array2=np.array(list2)
print(array2)

[1 2 3 4 5]
[1 2 3 4 5]


In [7]:
array1_type=type(array1)
array2_type=type(array2)
print(array1_type)
print(array2_type)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
mul=array1*array2
div=array1/array2
pow=array1**2
print(mul)
print(div)
print(pow)

[ 1  4  9 16 25]
[1. 1. 1. 1. 1.]
[ 1  4  9 16 25]


In [8]:
sin = np.sin(array1)
print("sin result for",array1,":",sin)
sin2 = np.sin(array2)
print("sin result for",array2,":",sin2)
log=np.log(array1)
print("log result for",array1,":",log)
log2=np.log(array2)
print("log result for",array2,":",log2)
exp=np.exp(array1)
print("expainstion result for",array1,":",exp)
exp2=np.exp(array2)
print("expainstion result for",array2,":",exp2)

sin result for [1 2 3 4 5] : [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
sin result for [1 2 3 4 5] : [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
log result for [1 2 3 4 5] : [0.         0.69314718 1.09861229 1.38629436 1.60943791]
log result for [1 2 3 4 5] : [0.         0.69314718 1.09861229 1.38629436 1.60943791]
expainstion result for [1 2 3 4 5] : [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
expainstion result for [1 2 3 4 5] : [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
